# Postgres
production:
  adapter: postgresql
  encoding: unicode
  database: polyptych_development
  pool: 15
  username: ben
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: polyptych_development
  pool: 15
  username: ben
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: polyptych_test
  pool: 15
  username: ben
  password:
